[package]
name = "kora-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Kora CLI Utilities"

[lints]
workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"
