[package]
name = "kora"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
kora-cli.workspace = true
kora-config.workspace = true
kora-service.workspace = true
kora-dkg.workspace = true
kora-runner.workspace = true
kora-domain.workspace = true

commonware-cryptography.workspace = true
commonware-codec.workspace = true

clap.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
eyre.workspace = true
serde_json.workspace = true
hex.workspace = true

[lints]
workspace = true
